modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ldtteam/ChatChainMC/issues/new"
[[mods]]
modId="chatchainmc"
version="${file.jarVersion}"
displayName="ChatChainMC"
authors="LDT Team"